name = "ilink-cloudflare"
main = "src/index.ts"
compatibility_date = "2026-03-26"

[vars]
ILINK_BASE_URL = "https://ilinkai.weixin.qq.com"

# 替换为你自己的 D1 数据库 ID。
[[d1_databases]]
binding = "DB"
database_name = "ilink-cloudflare"
database_id = "351eb10c-bec0-46d5-84d4-73920747ad33"
migrations_dir = "migrations"

# 替换为你自己的队列名。
[[queues.producers]]
binding = "NOTIFICATION_QUEUE"
queue = "ilink-notification-queue"

[[queues.consumers]]
queue = "ilink-notification-queue"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

